# Generated by Django 6.0 on 2026-01-16 01:16

import apps.producto.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(blank=True, default=apps.producto.models.Producto.generar_codigo, editable=False, null=True, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('intermedio', 'Intermedio'), ('dificil', 'Difícil')], max_length=20)),
                ('arreglista', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('portada', models.ImageField(upload_to='portadas/')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('tieneFinale', models.BooleanField(default=False)),
                ('tieneAudio', models.BooleanField(default=False)),
                ('tieneDestacado', models.BooleanField(default=False)),
                ('archivo', models.FileField(upload_to='files/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.categoriaproducto')),
            ],
        ),
    ]
