# Generated by Django 6.0 on 2026-01-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='code',
            new_name='uuidCode',
        ),
    ]
