# Generated by Django 6.0 on 2026-01-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('whatsappNumber', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('pagoId', models.IntegerField()),
            ],
        ),
    ]
