# Generated by Django 6.0 on 2026-01-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='pagoId',
            field=models.BigIntegerField(),
        ),
    ]
